nelmio_cors:
    defaults:
        origin_regex: true
        allow_credentials: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link', 'Authorization']
        max_age: 3600
    paths:
        '^/':
            allow_credentials: true  # Upewnij się, że ta wartość jest ustawiona
            allow_origin: ['http://localhost:3000']  # Ogranicz do zaufanych źródeł